### PR TITLE
More precise calculation for deposit gas

### PR DESCRIPTION
**Pull request by AlbertoElias**
We need to decide the buffer values to make it more precise. And do we need to apply this to other txs?

### CODE REVIEW

**Comment by krlosMata** [comment]
Other txs do not need this gas estimation since just `withdraw` and `withdrawCircuit` involves an ERC20 `transfer` and those txs do not depend on the smart contract state so their gas cost could be estimated accurately (from Metamask perspective).

Regarding adding `totalGasEstimated= transferERC20 + GAS_LIMIT_HIGH`, I think we should then remove 20000 from `GAS_LIMIT_HIGH` since stabdard ERC20 was included in this constant

**Comment by invocamanman** [comment]
> Other txs do not need this gas estimation since just `withdraw` and `withdrawCircuit` involves an ERC20 `transfer` and those txs do not depend on the smart contract state so their gas cost could be estimated accurately (from Metamask perspective).
> 
> Regarding adding `totalGasEstimated= transferERC20 + GAS_LIMIT_HIGH`, I think we should then remove 20000 from `GAS_LIMIT_HIGH` since stabdard ERC20 was included in this constant

good points! I think it's okay that leave that 20k gas more, because in the Smart contract the operation performed is `transferFrom` not `transfer` wich basically involves to update the allowance variable of the smart contract ( wich for a coincidence cost 20k ^^)

**Comment by krlosMata** [comment]
> > Other txs do not need this gas estimation since just `withdraw` and `withdrawCircuit` involves an ERC20 `transfer` and those txs do not depend on the smart contract state so their gas cost could be estimated accurately (from Metamask perspective).
> > Regarding adding `totalGasEstimated= transferERC20 + GAS_LIMIT_HIGH`, I think we should then remove 20000 from `GAS_LIMIT_HIGH` since stabdard ERC20 was included in this constant
> 
> good points! I think it's okay that leave that 20k gas more, because in the Smart contract the operation performed is `transferFrom` not `transfer` wich basically involves to update the allowance variable of the smart contract ( wich for a coincidence cost 20k ^^)

For user perspective I think it is better to approximate as much as we can but at the same tx could fail...so it's ok to no subtract 20000 gas xD

**Review by krlosMata — APPROVED** [review]
:smile_cat:

**Pull request merged**
