### PR TITLE
event on pr to main

### PR DESCRIPTION
**Pull request by krlosMata**
Trigger event to `integration-testing` when tagging new release candidate

### CODE REVIEW

**Review by AlbertoElias — APPROVED** [review]

**Comment by AlbertoElias** [comment]
@krlosMata Actually, I think it's better to leave as is. We aren't going to be doing rc releases in hermezjs, as the UIs use stable versions directly

**Comment by krlosMata** [comment]
> @krlosMata Actually, I think it's better to leave as is. We aren't going to be doing rc releases in hermezjs, as the UIs use stable versions directly

`hermezjs` could be used by third parties besides hermez wallet UI and it could need release candidates in order to not break integration between components. I think we should do release candidates and change-logs across all our repositories.

**Comment by AlbertoElias** [comment]
Changelogs for sure. But rc I don't think are necessary. Even with rc things can break, that's why we have tests and the rest of the process. But most projects and libraries only do betas and rcs before major releases, for feature and patch releases I don't think it's necessary.

**Review by AlbertoElias — APPROVED** [review]

**Comment by krlosMata** [comment]
agreement has been reached AFK to trigger `integration-testing` event on PR to `main`

**Pull request merged**
